[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "2.1.0"
python = ">=3.9,<3.13"
scipy = "1.11.3"
matplotlib = "^3.8.1"
